### ISSUE TITLE
Error detected while processing BufReadPost Autocommands for "*"... when opening .razor file

### ISSUE THREAD

**Issue by mparq** [tris203/rzls.nvim#33]
Full error: 
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...llar/neovim/HEAD-3c80348/share/nvim/runtime/filetype.lua:3
6: BufReadPost Autocommands for "*"..FileType Autocommands for "razor"..FileType Autocomman
ds for "razor": Vim(append):Error executing lua callback: ...r/neovim/HEAD-3c80348/share/nv
im/runtime/lua/vim/lsp.lua:355: Vim:Error executing vim.schedule lua callback: ...m/HEAD-3c
80348/share/nvim/runtime/lua/vim/lsp/client.lua:727: Vim:LSP[rzls]: Error ON_INIT_CALLBACK_
ERROR: "/Users/mparq/code/nvim-plugins/rzls.nvim/lua/rzls/init.lua:69: attempt to call fiel
d 'get_pipes' (a nil value)"

**Comment by mparq** [comment]
Created this issue mainly just so people could search the issues for this same problem. The issue is caused by #30 to allow launching from .cs file first. The fix is just to update roslyn.nvim plugin to latest.

**Comment by tris203** [comment]
Update rosllyn.nvim
