### ISSUE TITLE
cache_loader_lib: module 'rzls.roslyn_handlers' not found

### ISSUE THREAD

**Issue by drunkenQCat** [tris203/rzls.nvim#34]
the full report:
```
Failed to load `plugins.dotnet`

/home/drunkencat/.config/nvim/lua/plugins/dotnet.lua:29: module 'rzls.roslyn_handlers' not found:
	no field package.preload['rzls.roslyn_handlers']
	cache_loader: module 'rzls.roslyn_handlers' not found
	cache_loader_lib: module 'rzls.roslyn_handlers' not found
	no file './rzls/roslyn_handlers.lua'
	no file '/usr/share/luajit-2.1.0-beta3/rzls/roslyn_handlers.lua'
	no file '/usr/local/share/lua/5.1/rzls/roslyn_handlers.lua'
	no file '/usr/local/share/lua/5.1/rzls/roslyn_handlers/init.lua'
	no file '/usr/share/lua/5.1/rzls/roslyn_handlers.lua'
	no file '/usr/share/lua/5.1/rzls/roslyn_handlers/init.lua'
	no file './rzls/roslyn_handlers.so'
	no file '/usr/local/lib/lua/5.1/rzls/roslyn_handlers.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/rzls/roslyn_handlers.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './rzls.so'
	no file '/usr/local/lib/lua/5.1/rzls.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/rzls.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - ~/.config/nvim/lua/plugins/dotnet.lua:29 _in_ **load**
  - ~/.config/nvim/lua/config/lazy.lua:17
  - ~/.config/nvim/init.lua:2
```
the config file in lazyvim:
```lua
-- plugins/dotnet.lua
return {
  {
    "seblj/roslyn.nvim",
    opts = {
      args = {
        "--logLevel=Information",
        "--extensionLogDirectory=" .. vim.fs.dirname(vim.lsp.get_log_path()),
        "--razorSourceGenerator=" .. vim.fs.joinpath(
          vim.fn.stdpath("data") --[[@as string]],
          "mason",
          "packages",
          "roslyn",
          "libexec",
          "Microsoft.CodeAnalysis.Razor.Compiler.dll"
        ),
        "--razorDesignTimePath=" .. vim.fs.joinpath(
          vim.fn.stdpath("data") --[[@as string]],
          "mason",
          "packages",
          "rzls",
          "libexec",
          "Targets",
          "Microsoft.NET.Sdk.Razor.DesignTime.targets"
        ),
      },
      config = {
        on_attach = LazyVim.lsp.on_attach,
        capabilities = {},
        handlers = require("rzls.roslyn_handlers"),
        settings = {
          ["csharp|inlay_hints"] = {
            csharp_enable_inlay_hints_for_implicit_object_creation = true,
            csharp_enable_inlay_hints_for_implicit_variable_types = true,
            csharp_enable_inlay_hints_for_lambda_parameter_types = true,
            csharp_enable_inlay_hints_for_types = true,
            dotnet_enable_inlay_hints_for_indexer_parameters = true,
            dotnet_enable_inlay_hints_for_literal_parameters = true,
            dotnet_enable_inlay_hints_for_object_creation_parameters = true,
            dotnet_enable_inlay_hints_for_other_parameters = true,
            dotnet_enable_inlay_hints_for_parameters = true,
            dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix = true,
            dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name = true,
            dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent = true,
          },
        },
      },
    },
  },
  {
    "tris203/rzls.nvim",
    opts = {
      config = {
        on_attach = LazyVim.lsp.on_attach,
        capabilities = {},
        path = "/.local/share/nvim/mason/packages/rzls",
      },
    },
  },
}
```
and also, I've already installed the lsp `roslyn`, `rzls` from mason. but apparently, the rzls.nvim cannot find the dynamic library files from right place. is there any way to solve it?

**Comment by tris203** [comment]
https://github.com/tris203/.dotfiles/blob/main/nvim%2Flua%2Fcustom%2Fplugins%2Froslyn.lua

Here is an example from my dotfiles

**Comment by drunkenQCat** [comment]
ok, mindblowing.. I will try it later.

**Comment by drunkenQCat** [comment]
wait, hold on, I found that the rzls was insatlled to ~/code/rzls.nvim

**Comment by tris203** [comment]
You'll need to comment the `dev = true`

**Comment by drunkenQCat** [comment]
here comes new error:

```
Error executing lua callback: BufReadPost 自动命令 "*": Vim(append):Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:36: BufReadPost 自动命令 "*"..FileType 自动命令 "razor": Vim(append):Error executing lua callback: ....local/share/nvim/lazy/rzls.nvim/lua/rzls/server/lsp.lua:79: /usr/share/nvim/runtime/lua/vim/lsp/client.lua:583: server sent empty result
stack traceback:
	[builtin#36]: at 0x7fcea6725140
	....local/share/nvim/lazy/rzls.nvim/lua/rzls/server/lsp.lua:79: in function 'request'
	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:581: in function 'initialize'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:467: in function 'start_client'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:274: in function 'start'
	...encat/.local/share/nvim/lazy/rzls.nvim/lua/rzls/init.lua:104: in function <...encat/.local/share/nvim/lazy/rzls.nvim/lua/rzls/init.lua:53>
	[C]: in function 'nvim_cmd'
	/usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35>
	[C]: in function 'pcall'
	vim/shared.lua: in function <vim/shared.lua:0>
	[C]: in function '_with'
	/usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
	[C]: at 0x55d4e16f5db5
	[C]: in function 'pcall'
	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:349: in function 'open_in_new_window'
	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:402: in function 'fn'
	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:228: in function 'edit'
	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:245: in function <...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:236>
stack traceback:
	[C]: in function '_with'
	/usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
	[C]: at 0x55d4e16f5db5
	[C]: in function 'pcall'
	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:349: in function 'open_in_new_window'
	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:402: in function 'fn'
	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:228: in function 'edit'
	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:245: in function <...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:236>
stack traceback:
	[C]: in function 'winsaveview'
	.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:358: in function 'get_offset'
	...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:171: in function 'refresh'
	...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:127: in function 'debounced_refresh'
	...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:143: in function 'debounced_refresh'
	...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:27: in function <...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:26>
```

**Comment by tris203** [comment]
What happens if you run `:checkhealth rzls`

**Comment by drunkenQCat** [comment]
rzls:                                           require("rzls.health").check()

rzls.nvim report ~
- ERROR roslyn pipe not connected

rzls.nvim logs ~

rzlsnvim logs: ~
- [rzlsnvim][2024-12-01 20:38:01] Ran Setup

**Comment by tris203** [comment]
Is that once you have opened a razor file

**Comment by drunkenQCat** [comment]
yes, I was stucked when move cursor. after a while, the diagnose windows appeared.

> here comes new error:
> 
> ```
> Error executing lua callback: BufReadPost 自动命令 "*": Vim(append):Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:36: BufReadPost 自动命令 "*"..FileType 自动命令 "razor": Vim(append):Error executing lua callback: ....local/share/nvim/lazy/rzls.nvim/lua/rzls/server/lsp.lua:79: /usr/share/nvim/runtime/lua/vim/lsp/client.lua:583: server sent empty result
> stack traceback:
> 	[builtin#36]: at 0x7fcea6725140
> 	....local/share/nvim/lazy/rzls.nvim/lua/rzls/server/lsp.lua:79: in function 'request'
> 	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:581: in function 'initialize'
> 	/usr/share/nvim/runtime/lua/vim/lsp.lua:467: in function 'start_client'
> 	/usr/share/nvim/runtime/lua/vim/lsp.lua:274: in function 'start'
> 	...encat/.local/share/nvim/lazy/rzls.nvim/lua/rzls/init.lua:104: in function <...encat/.local/share/nvim/lazy/rzls.nvim/lua/rzls/init.lua:53>
> 	[C]: in function 'nvim_cmd'
> 	/usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35>
> 	[C]: in function 'pcall'
> 	vim/shared.lua: in function <vim/shared.lua:0>
> 	[C]: in function '_with'
> 	/usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
> 	[C]: at 0x55d4e16f5db5
> 	[C]: in function 'pcall'
> 	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:349: in function 'open_in_new_window'
> 	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:402: in function 'fn'
> 	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:228: in function 'edit'
> 	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:245: in function <...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:236>
> stack traceback:
> 	[C]: in function '_with'
> 	/usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
> 	[C]: at 0x55d4e16f5db5
> 	[C]: in function 'pcall'
> 	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:349: in function 'open_in_new_window'
> 	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:402: in function 'fn'
> 	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:228: in function 'edit'
> 	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:245: in function <...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:236>
> stack traceback:
> 	[C]: in function 'winsaveview'
> 	.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:358: in function 'get_offset'
> 	...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:171: in function 'refresh'
> 	...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:127: in function 'debounced_refresh'
> 	...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:143: in function 'debounced_refresh'
> 	...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:27: in function <...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:26>
> ```

**Comment by tris203** [comment]
I want to see the checkhealth with a razor file open. 

This is nothing wrong with this plugin this is other combos of your other plugins

**Comment by drunkenQCat** [comment]
[rzls_report120124.txt](https://github.com/user-attachments/files/17969211/rzls_report120124.txt)

**Comment by tris203** [comment]
Have you got the html lsp installed?

**Comment by drunkenQCat** [comment]
yes, it's installed.

**Comment by tris203** [comment]
This is not an issue with the plugin but instead with your neovim configuration.

If you need further help, you can ask in rzls discord, lazyvim matrix or reddit
