### ISSUE TITLE
All razor files in repo gets initialized. Is it possible to improve performance here?

### ISSUE THREAD

**Issue by daveHylde** [tris203/rzls.nvim#35]
First of all THANK YOU!!!! I've worked in blazor for 6 months now with no lsp for the razor files, and this plugin has been a revelation and a lifesaver. I can see I gave up looking for a solution juuust before this plugin was created. 😅 

This issue is more a request as I'm just happy to finally have lsp support in neovim for blazor. I see that all razor files initializes a buffer on init, and this causes long startup time and a lot of buffer overhead. Is it possible to tweak this? Completely understand if not, as this is Microsoft we're dealing with - and they tend to have a certain way of complicating things.

Much appreciation from me  - keep up the great work!

![image](https://github.com/user-attachments/assets/e6513b56-865b-4d63-9fab-2470d9bc6300)

**Comment by tris203** [comment]
I dont' think so @daveHylde 

Even if i remove the code in the plugin that does it, then rzls does it anyways. So its almost easier to do it ourselves so that we have control over it. And from my memory of the source code, I think preloading and opening the files is what the VsCode extension does too.

I haven't tried in a project that big, does it cause a noticeable lag when first opening? Is it fairly responsive once its open and working?

Although if you want to fork and try anything for performance, PRs are greatly received! Im sure there could be something I have overlooked

Ps, if you want to get really excited checkout the open PR for the `razor_ts` branch. I have a _nearly_ fully working treesitter grammar for razor

**Comment by tris203** [comment]
I tried some coutine wrapping, which I think makes it better

Could you test the `perf` branch and see if its better for you

**Comment by daveHylde** [comment]
Thanks for being on this so fast. 🏆 

I did suspect that this is a Microsoft design issue, and I think you're right. Thinking back to my vscode days I remember it taking long to initialize a blazor project as well. 

The `perf` branch fails for me on startup with:

```sh
Error detected while processing User Autocommands for "RoslynInitialized":
Error executing lua callback: ...vimPackages/start/vimplugin-rzls/lua/rzls/server/lsp.lua:79: ...wrapped-0.10.2/share/nvim/runtime/lua/vim/lsp/client.lua:643: bufnr: expected number, got function
stack traceback:
        [builtin#36]: at 0x7f3dbdb31e00
        ...vimPackages/start/vimplugin-rzls/lua/rzls/server/lsp.lua:79: in function 'request'
        ...wrapped-0.10.2/share/nvim/runtime/lua/vim/lsp/client.lua:679: in function 'request'
        ....10.2/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:297: in function 'send_request'
        ....10.2/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:715: in function 'force_refresh'
        ...Packages/start/vimplugin-rzls/lua/rzls/documentstore.lua:170: in function 'initialize'
        .../myNeovimPackages/start/vimplugin-rzls/lua/rzls/init.lua:76: in function <.../myNeovimPackages/start/vimplugin-rzls/lua/rzls/init.lua:75>
        [C]: in function 'nvim_exec_autocmds'
        ...NeovimPackages/start/vimplugin-roslyn/lua/roslyn/lsp.lua:35: in function 'handler'
        ...wrapped-0.10.2/share/nvim/runtime/lua/vim/lsp/client.lua:1007: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

When it did start up it did appear to still initiate all files. It works fairly smooth when initialized, but the startup time is about 30-60sec on a large project like the one I'm working on (on a pretty powerfull machine running NixOS). 

If I find a chance to contribute I will - would be fun to learn more lua and get into how neovim plugins actually work. 😆

For now I hope that good bug rapports will at least be of some help. 😄 

And again - really good work from your side!

**Comment by tris203** [comment]
I think i might have used a nightly only way to speed it up (using the `:` methods on the lsp client object)

Could you give the perf branch a try with nightly?

**Comment by daveHylde** [comment]
I've now tried the `perf` branch  on neovim nightly and it may feel a tiny bit faster, but could be placebo. 😄 

I still see all the buffers being initialized, so I think you right in assuming this is a MS thing. 

Do you think it's possible to do the initialization  on a different thread than the ui thread? The razor startup time is what it is, and think it's unavoidable with the way it's designed atm - but the initialization blocks the ui thread so nvim takes a good minute before it's properly interactive in a large blazor repo.

**Comment by tris203** [comment]
Thats exactly the change in the perf branch.

The UI shouldn't block as the project is initialising

**Comment by daveHylde** [comment]
Nice 😄 
It's more smooth, but still seems to struggle a bit with the large project. But now that I've switched a bit back and forth it's much more smooth. 

Seriously, great job! Really appreciate this. This plugin is such a quality of life improvement for  me

**Comment by neubaner** [comment]
VSCode also initializes all files and watches for any new razor files:
https://github.com/dotnet/vscode-csharp/blob/69234b01bba73e804448598c53d7486b8a26462e/src/razor/src/document/razorDocumentManager.ts#L91-L122

Just Microsoft for you :)

**Comment by tris203** [comment]
> VSCode also initializes all files and watches for any new razor files:
> https://github.com/dotnet/vscode-csharp/blob/69234b01bba73e804448598c53d7486b8a26462e/src/razor/src/document/razorDocumentManager.ts#L91-L122
> 
> Just Microsoft for you :)

Although it's better now. Look at line 104. 

That's what we're trying to achieve in #38

**Comment by tris203** [comment]
@daveHylde if you want to test #38

Now would be good. Make sure your rzls and Roslyn servers at at latest (not sure if they are in nixpkgs yet)

**Comment by tris203** [comment]
A new issue is probably best. The changes were required to work with the new roslyn and razor LSPs.
