### ISSUE TITLE
LazyVim setup

### ISSUE THREAD

**Issue by andresparrab** [tris203/rzls.nvim#40]
Hello!
First I want to say awesome that finally we can get  blazor support in nvim.
Im using Lazynvim that works really great with omnisharp, omnishapr_extended, code actions and everything out of the box

But i can just get rzls to work.
I have installed the rzls.nvim ans roslyn via mason..
I have tryed many things but i dont know enough to make it work..this is my setting right now in a fule called roslyn.lua
and it is indded installed wit mason but it complains that i cant download roslyn via lazy 

What is the correct way to implemnt this?

But i can get the config to work:

```lua


return {
  {
    "roslyn",
    opts = {
      args = {
        "--logLevel=Information",
        "--extensionLogDirectory=" .. vim.fs.dirname(vim.lsp.get_log_path()),
        "--razorSourceGenerator=" .. vim.fs.joinpath(
          vim.fn.stdpath("data") --[[@as string]],
          "mason",
          "packages",
          "roslyn",
          "libexec",
          "Microsoft.CodeAnalysis.Razor.Compiler.dll"
        ),
        "--razorDesignTimePath=" .. vim.fs.joinpath(
          vim.fn.stdpath("data") --[[@as string]],
          "mason",
          "packages",
          "rzls",
          "libexec",
          "Targets",
          "Microsoft.NET.Sdk.Razor.DesignTime.targets"
        ),
      },
      handlers = "rzls.roslyn_handlers",
    },
  },
}


  ```

**Comment by andresparrab** [comment]
Hello!
Thank you for quick response
Yes I have read the lazyvim documentation and try their examples.. They write  nontonwritw the word dependencies or 'require' and to write in another way but I totally failed.. Thank you for provide you example file on how you did implement it.. Was this in lazyvim?
I will try when I arrive home but I am very excited to try your example and it it work you make my Christmas.. Really

**Comment by tris203** [comment]
Its not in lazyvim, but it is using lazy.nvim which is the package manager that LazyVim uses. if you need more help there is a discord link on the discussions page where you will be able to get help

Blazor in Neovim is a lot better than it was 6 months ago, but its still not the smoothest. But we are working on it
